# Generated by Django 5.2.8 on 2025-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='TODO title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('due_date', models.DateField(blank=True, help_text='When is this due?', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Is this completed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
